name: poetry install
description: 'Install a Python package using Poetry'
inputs:
  python-version:
    description: 'Python version to install (defaults to 3.12)'
    default: "3.12"
  groups:
    description: 'Groups to include, as a json list'
    default: "[]"

runs:
  using: "composite"
  steps:
    - name: Build groups argument
      shell: bash
      run: |
        GROUPS_ARG=" --only ${element} ${{ join(fromJSON(inputs.groups), ',') }}"
        echo "GROUPS_ARG=${GROUPS_ARG}" >> $GITHUB_ENV
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install poetry
      uses: abatilo/actions-poetry@v2
    - name: Install poetry-monoranger-plugin
      shell: bash
      run: |
        poetry self add poetry-monoranger-plugin
    - name: Install package
      shell: bash
      run: |
        poetry install${GROUPS_ARG}
